### ISSUE TITLE
Expose setBackend endpoint

### ISSUE THREAD

**Issue by filahf** [cloud-annotations/javascript-sdk#10]
Would it be possible to expose a backend setter in this SDK, or is this library built around the CPU backend? 

I would like to experiment with different backends and see their performance on mobile devices. According to the [docs](https://www.tensorflow.org/js/guide/platform_environment) WebGL should be most efficient of the alternatives.

**Comment by bourdakos1** [comment]
If you import TensorFlow.js alongside the SDK you can change the backend to whatever you want (with one caveat)

The SDK uses whatever backend has been set or the default (which is webgl if you browser supports it). The SDK only uses that backend for the for the first portion of the model which is GPU intensive, it then switches to CPU at the end for doing the ops that aren’t very efficient on the GPU.

We could maybe add a flag so that it doesn’t switch between CPU and WebGL, that way it will use whatever you set with TensorFlow.js for the entire model

**Comment by filahf** [comment]
Ah I see, my bad, I skimmed through the code and interpreted it as being CPU from beginning to end.

Do you reckon a pure WebGL run would benefit a modern smartphone or is the current setup with a combination of the both superior there as well? Otherwise a flag might be unnecessary, at least for my use case

**Comment by bourdakos1** [comment]
Yea I think the WebGL + CPU combo would still be superior. The only portion that runs on CPU is non-max suppression which is a very quick operation that can’t take advantage of the parallelizarion of WebGL with the added overhead of creating/loading the textures
